### ISSUE TITLE
Add more i18n/t10n packages.

### ISSUE THREAD

**Issue by ascherer** [debbuild/debbuild#104]
Please take a look at [debbuild.pot](https://github.com/ascherer/debbuild/blob/master/po/debbuild.pot) and create a new translation with
```
msginit --input=po/debbuild.pot --locale=YOUR-FAVORITE-LANGUAGE --output=po/YOUR-FAVORITE-LANGUAGE/debbuild.po
msgfmt --output-file=po/YOUR-FAVORITE-LANGUAGE/debbuild.mo po/YOUR-FAVORITE-LANGUAGE/debbuild.po
```
where `YOUR-FAVORITE-LANGUAGE` should be a two-character country code.

**Comment by Conan-Kudo** [comment]
@ascherer You may want to consider wiring the project up with a service like [Zanata](http://zanata.org/) or [Weblate](https://weblate.org/) to enable translations.

**Comment by ascherer** [comment]
I'd rather invoke help from [TP](https://translationproject.org/html/welcome.html).

**Comment by Conan-Kudo** [comment]
That works too...

**Comment by ascherer** [comment]
I've never heard back from them, neither for `debbuild` nor for `cwebbin`.

**Comment by ascherer** [comment]
So weblate it is.
