### ISSUE TITLE
cwebbin.spec breaks with debbuild 19.11.0

### ISSUE THREAD

**Issue by ascherer** [debbuild/debbuild#131]
The recent reversion (commit 14c6ffb22fd35f24df5a75c934977a96207521ea) breaks my [`cwebbin.spec`](https://github.com/ascherer/cwebbin/blob/master/cwebbin.spec#L140).

Here I replace the string(s) `\[at]` with single `@` for the cweb/ctwill manpages in TeX Live (the resulting string `@VERSION@` itself is replaced by the TeX Live build system later). The `-e` option with the _five_ consecutive backslashes works definitively with **GNU sed on Linux** and in part with **BSD sed on macOS** (at least when the (input) file argument `$m.1` is moved to the end of the command line).

Please provide a way to use backslashes in specfiles/shell scripts as in version 19.5.0 and earlier.

**Comment by Conan-Kudo** [comment]
@ascherer Does this behavior work as expected with `rpmbuild(8)`?

**Comment by ascherer** [comment]
Excerpts from `*build -bi --with texlive -v SPECS/cwebbin.spec`:

**rpmbuild 4.14.1**
```
+ /bin/sed ctwill.1 -e /Web2c/ s/\\\[at\]/@/g
+ /bin/sed cweb.1 -e /Web2c/ s/\\\[at\]/@/g
```

**debbuild 19.5.0**
```
+ /bin/sed ctwill.1 -e /Web2c/ s/\\\[at\]/@/g
+ /bin/sed cweb.1 -e /Web2c/ s/\\\[at\]/@/g
```

**debbuild 19.11.0**
```
+ /bin/sed ctwill.1 -e /Web2c/ s/\[at\]/@/g
+ /bin/sed cweb.1 -e /Web2c/ s/\[at\]/@/g
```
Note the _missing_ escaped backslashes.

So, yes **rpmbuild** creates `cweb-texlive.tar.gz` with correct content, but **debbuild 19.11.0** does not.

**Comment by Conan-Kudo** [comment]
@daxelrod-datto Please take a look at this and see what we can do here.

**Comment by daxelrod-datto** [comment]
Thank you for the additional detail, @ascherer .

Just to set expectations, I think that it will take me several weeks before I have the bandwidth to work on this.

**Comment by ascherer** [comment]
No worries, I'm using version 19.5.0 for the time being. TeX Live 2020 ccode freeze is scheduled for Feb/Mar next year, and there's also a [bug in Pandoc](https://github.com/jgm/pandoc/issues/5929) to be fixed for `cwebbin.spec` to work with the latest release.

**Comment by ascherer** [comment]
[Preliminary analysis](https://github.com/debbuild/debbuild/commit/14c6ffb22fd35f24df5a75c934977a96207521ea#commitcomment-36208590).

**Comment by ascherer** [comment]
All my test specfiles work nicely, even the MWE works for both macros. Please test your own specfile with ` \\n`.
