### ISSUE TITLE
%patchN macros broken in git master

### ISSUE THREAD

**Issue by Conan-Kudo** [debbuild/debbuild#135]
It seems that usage of the `%patch`/`%patchN` macros are broken in debbuild right now.

Some git bisecting digging led to d3787e55c9511fea136cdb7d6b5559ae69bd7460 being the cause of breaking this.

@ascherer, @daxelrod-datto, either of you have any idea how to fix this? My guess is that the regex change causes it to think that it's an external macro rather than an internal one to process.

**Comment by Conan-Kudo** [comment]
Note that this doesn't impact `%autosetup`/`%autopatch`, as those are defined as regular macros rather than built-ins like `%patch`/`%patchN` macros are.

**Comment by ascherer** [comment]
Confirmed. It's the `eq` in [line 544](https://github.com/debbuild/debbuild/blob/master/debbuild#L544) that fails to match `patchN` (with numerical `N`). If you use `%patch -P 0`, it will work. I'll submit a fix soon.

**Comment by Conan-Kudo** [comment]
Fixed in master now.
