### ISSUE TITLE
Requires(post) and Requires(postun) are ignored

### ISSUE THREAD

**Issue by dwminer** [debbuild/debbuild#141]
Debian has no concept of a postinstall dependency, but instead of completely dropping this kind of dependency, we should instead convert it to a regular dependency and warn the user.

**Comment by Conan-Kudo** [comment]
Wow, you're right! I'm not sure how this was never noticed.

It definitely makes sense to "upgrade" the dependency to `Requires` (`Depends`) in that scenario.

There's some similar prior art in debbuild for doing "downgrades" of `Supplements` to `Enhances`, as Debian doesn't support Supplements:

https://github.com/debbuild/debbuild/blob/f1771c31230e3974dfd5b9abba97e7f83f52bbc3/debbuild#L851-L855
