### ISSUE TITLE
Supplements is ignored in subpackages

### ISSUE THREAD

**Issue by dwminer** [debbuild/debbuild#143]
Seems like in the subpackage-specific logic (which really shouldn't exist), `Supplements` gets completely ignored. This is a weak dependency, so the closest Debian equivalent is probably `Enhances`.

**Comment by Conan-Kudo** [comment]
Yikes! It should be quite easy to fix, though! 

We have existing logic for doing this for the main package that can be adapted for subpackages:

https://github.com/debbuild/debbuild/blob/f1771c31230e3974dfd5b9abba97e7f83f52bbc3/debbuild#L851-L855
