### ISSUE TITLE
%debian_version is not set on build.opensuse.org trying to use Debian:Next

### ISSUE THREAD

**Issue by ailin-nemui** [debbuild/debbuild#157]
I have a conditional in my spec file which is supposed to use the packlist macro only on some systems (not on Debian):

however, on my repo on build.opensuse.org which includes Debian:debbuild, the debian_version ends up being empty:

```
Name: dump
Version: 1
BuildRequires: perl
BuildRequires: debhelper fakeroot perl-deb-macros

%dump

%build
%if 0%{?fedora} != 0 || 0%{?rhel_version} != 0 || 0%{?debian_version} != 0 || 0%{?ubuntu_version} != 0
echo no packlist
%else
echo with packlist
%perl_process_packlist
%endif


%changelog
```

The dump instruction shows
```
%debian_version ==> 
```

There is also a warning
```
Use of uninitialized value $specglobals{"debian_version"} in concatenation (.) or string at /usr/bin/debbuild line 481, <$fh> line 6.
```

**Comment by Conan-Kudo** [comment]
I'm pretty sure this is because we do the population of macros in the wrong order...

https://github.com/debbuild/debbuild/blob/3555b6f6f38c58de48acbd70e844a20875c263cb/debbuild#L111-L119

**Comment by Conan-Kudo** [comment]
Actually, it's not quite so straightforward. The `lsb_detection` subroutine is used to populate the distribution macros, including `%dist`, which means some care needs to be taken to handle the undefined case properly...

https://github.com/debbuild/debbuild/blob/3555b6f6f38c58de48acbd70e844a20875c263cb/debbuild#L318-L360

**Comment by ailin-nemui** [comment]
I believe this issue may have been introduced by 0a73e8acfb41684b18a2ffdadba67c3fb8bff20a

This seems to override debian and debian_version, and does not properly follow the build service macros either (unlike claimed in the commit message), those set debian_version to debian * 100 + patch_level

In fact, this breaks a previously working spec file using conditionals like
```
dev
%if 0%{?debian_version} > 800 || 0%{?ubuntu_version} > 1510
BuildRequires:  libutf8proc-dev
%endif
```

I think if we revert this commit, this issue can be corrrected

**Comment by Conan-Kudo** [comment]
I may rip that out for other reasons, but OBS also sets the `%debian` and `%ubuntu` macros. Those are supposed to work when overridden.

**Comment by ailin-nemui** [comment]
You could additionally replace 
```
$specglobals{$baseos} = $specbasever;
``` with 
```
$specglobals{$baseos} //= $specbasever;
```

thus not overwriting a value if it has already been set from .debmacros

**Comment by Conan-Kudo** [comment]
@ailin-nemui Feel up to sending a PR to fix this? Contributions are welcome (I can easily review and push a fix once merged, but I don't have time at the moment to write the fix myself).

**Comment by ailin-nemui** [comment]
I opened #158
