### ISSUE TITLE
Unresolved macros are not handled properly - 22.02.0

### ISSUE THREAD

**Issue by Conan-Kudo** [debbuild/debbuild#213]
With debbuild 22.02.0, the following snippet at the top of a spec file doesn't work:

```rpmspec
%global libsomajor 1
%if "%{_vendor}" == "debbuild"
%global libname lib%{name}%{libsomajor}
%global devname lib%{name}-dev
%else
%global libname lib%{name}
%global devname lib%{name}-devel
%endif

Name: foo
```

Older versions handle this properly be turning macros like `%libname` into `lib%{name}1` (which debbuild will re-expand later), but debbuild 22.02.0 turns this into `lib%name1` which is not valid. It works properly with rpmbuild on CentOS 9 as well.

This is certainly related to @vzhestkov's changes to the macro engine.

**Comment by Conan-Kudo** [comment]
@vzhestkov, can you please take a look?

**Comment by Conan-Kudo** [comment]
Sample from the build log:

```
[  158s] Executing (package-creation): /bin/bash -e /var/tmp/deb-tmp.pkg.97769 for lib%name1
[  158s] + umask 022
[  158s] + cd /home/abuild/debbuild/BUILD
[  158s] + /usr/bin/fakeroot -- /usr/bin/dpkg-deb -b /home/abuild/debbuild/BUILDROOT/nispor-1.2.3-2ubuntu20.04.amd64/lib%name1 /home/abuild/debbuild/DEBS/amd64/lib%name1_1.2.3-2ubuntu20.04_amd64.deb
[  158s] dpkg-deb: error: parsing file '/home/abuild/debbuild/BUILDROOT/nispor-1.2.3-2ubuntu20.04.amd64/lib%name1/DEBIAN/control' near line 1:
[  158s]  invalid package name in 'Package' field: character '%' not allowed (only letters, digits and characters '-+._')
[  158s] Exec of /var/tmp/deb-tmp.pkg.97769 failed (%pkg): 512
```

This is reproduced here: https://build.opensuse.org/package/live_build_log/home:Pharaoh_Atem:debbuild-test/nispor/xUbuntu_20.04/x86_64

cc: @vzhestkov

**Comment by vzhestkov** [comment]
@Conan-Kudo sure, will check

**Comment by Conan-Kudo** [comment]
@vzhestkov, thank you!
