### ISSUE TITLE
%systemd_user_preun does not expand correctly

### ISSUE THREAD

**Issue by Conan-Kudo** [debbuild/debbuild#216]
When trying to use `%systemd_user_preun`, debbuild expands the macro and only prints out the first line, like so:

```
root@build:/# debbuild -E "%systemd_user_preun foo.service"

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then\ 
```

In contrast to `%systemd_preun`, which works fine:

```
root@build:/# debbuild -E "%systemd_preun foo.service"

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
        # Package removal, not upgrade
        systemctl --no-reload disable foo.service > /dev/null 2>&1 || :
        systemctl stop foo.service > /dev/null 2>&1 || :
fi
```

**Comment by Conan-Kudo** [comment]
@vzhestkov Do you have any idea what's going on here? This seems to be an odd breakage.

The macros come from `macros.systemd` from debbuild-macros.

**Comment by vzhestkov** [comment]
Will check :+1:

**Comment by vzhestkov** [comment]
Actually the root cause that `%systemd_user_preun` is the only defined with the space at the end of first line:
```
%systemd_user_preun() \
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then\ 
        # Package removal, not upgrade \
        systemctl --no-reload --user --global disable %{?*} > /dev/null 2>&1 || : \
fi \
%{nil}
```
It's not visible here, but you can check the source. Such definition causing the error in RPM also:
```
# rpm -E '%TEST_systemd_user_preun'
error: /usr/lib/rpm/macros.d/macros.test: line 6: Macro % has illegal name (%define)

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
```
Do we really need to fix it? Or maybe fix the macros file?
