### ISSUE TITLE
Depends list in control file changes order? / reproducible build

### ISSUE THREAD

**Issue by ailin-nemui** [debbuild/debbuild#217]
Hi, (not sure if this is the right place)

I'm looking into an issue where the opensuse build service rebuilds my packages, and publishes needless "rebuilt" versions.

The only difference seems to be the order of the Depends: line in the control file. I wonder where the root problem of that lies.

```
diff -apru 9.4/control/control 9.5/control/control
--- 9.4/control/control 2022-04-25 18:02:36.000000000 +0200
+++ 9.5/control/control 2022-04-29 14:52:41.000000000 +0200
@@ -1,5 +1,5 @@
 Package: irssi
-Version: 1.2.3-9.4
+Version: 1.2.3-9.5
 Section: net
 Priority: optional
 Architecture: amd64
@@ -14,5 +14,5 @@ Description: Modular, Secure, and Well D
  Irssi is not using the ircII code.
 Homepage: http://www.irssi.org
 Recommends: irssi-python2
-Depends: liblwp-protocol-https-perl,libotr5,libgcrypt20,libc6,libgpg-error0,libperl5.30,libcrypt1,libglib2.0-0,libssl1.1,libutf8proc2,libtinfo6,libpcre3
+Depends: liblwp-protocol-https-perl,libglib2.0-0,libssl1.1,libutf8proc2,libtinfo6,libc6,libpcre3,libperl5.30,libcrypt1,libotr5,libgcrypt20,libgpg-error0
 Conflicts: irssi,irssi-snapshot,irssi-plugin-otr,irssi-otr
```

[irssi_1.2.3-9.4_amd64.deb.zip](https://github.com/debbuild/debbuild/files/8632575/irssi_1.2.3-9.4_amd64.deb.zip)
[irssi_1.2.3-9.5_amd64.deb.zip](https://github.com/debbuild/debbuild/files/8632576/irssi_1.2.3-9.5_amd64.deb.zip)

https://build.opensuse.org/package/show/home:ailin_nemui:irssi-test/irssi

**Comment by Conan-Kudo** [comment]
That is an OBS thing, and not a debbuild thing. It happens because OBS detected the dependency chain churning and triggered rebuilds automatically.
