### ISSUE TITLE
Dependency tracking broken on Ubuntu 23.04 (usrmerge related?)

### ISSUE THREAD

**Issue by ailin-nemui** [debbuild/debbuild#230]
Example from the log file:

```
[   31s] Checking library requirements...
[   31s] dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libglib-2.0.so.0
```

https://packages.ubuntu.com/search?suite=lunar&arch=any&mode=exactfilename&searchon=contents&keywords=libglib-2.0.so.0

according to package search the library is in "/usr/lib/...."

Maybe related to https://groups.google.com/g/linux.debian.bugs.dist/c/xBZfbubcVCw 

Result are packages with missing dependencies

**Comment by Conan-Kudo** [comment]
Yeah, this is probably related to usrmerge 😦

**Comment by Conan-Kudo** [comment]
Feel free to submit a pull request and we can review it properly. 😄
