### ISSUE TITLE
Source does not currently expand macros

### ISSUE THREAD

**Issue by artman41** [debbuild/debbuild#241]
We have a situation where we define the name of the .tar.gz prior to calling rpmbuild and then use that macro as 

```spec
Source: ${my_src_tgz}
```

with debbuild, this currently fails as the macro isn't expanded.

https://github.com/debbuild/debbuild/blob/fb4e6320e58897b753448c21c65ef4cd8f6e9cc8/debbuild#L1171-L1182

ideally, a call to `expandmacros` would be done after defining `$filename`

**Comment by Conan-Kudo** [comment]
You mean with `%{my_src_tgz}` or something similar (like `%{pypi_source %{name}}`)?

**Comment by artman41** [comment]
@Conan-Kudo specifically, this is the excerpt from the .spec:

```spec
Source:     %{otp_source_tgz}
```

with the rpmbuild command being

```bash
rpmbuild --define '_tmppath /home/docker/.tmp' --define 'otp_source otp-OTP-18.0' --define 'otp_source_tgz otp-OTP-18.0.tar.gz' --define 'before22 true' --define 'osarch el8' --define 'otp_version 18.0' --define 'erts_version 7.0' --define 'erl_configure --enable-builtin-zlib  --with-ssl=/usr/local/openssl-1.0.2r --enable-hipe --enable-smp-support --enable-threads --with-wx --with-wxdir=/usr/lib64/wx/ --with-wx-config=' --define 'prefix ZLIB_INCL-' -ba /home/docker/rpmbuild/SPECS/otp_erlang.spec
```
