### ISSUE TITLE
Expired release key (Ubuntu) 

### ISSUE THREAD

**Issue by dominicbr** [debbuild/debbuild#250]
The release key for `Ubuntu:debbuild` appears to have [expired](https://build.opensuse.org/projects/Ubuntu:debbuild/signing_keys):

We're seeing the following from our CICD infra:

```
The following signatures were invalid: EXPKEYSIG 08CF86BF009AAE2E Ubuntu:debbuild OBS Project <Ubuntu:debbuild@build.opensuse.org>
```

**Comment by Conan-Kudo** [comment]
This is fixed now.
