### ISSUE TITLE
License %license under %files section mentioned in *.SPEC file install to: %{_datadir}/%{_docdir}/%{name}/ instead of: %{_datadir}/licenses/%{name}/ directory

### ISSUE THREAD

**Issue by MartinVonReichenberg** [debbuild/debbuild#256]
As mentioned in the header, every time I use **DebBuild** for building packages from the `*.SPEC` template, `%license` files mentioned in the `%files` section, go after building `*.DEB` package into: `%{_datadir}/%{_docdir}/%{name}/` instead of: `%{_datadir}/licenses/%{name}/`, even after explicitly mentioning _(redundant)_ `install` commands for each LICENSE or DOCUMENT.
The issue can be (re)viewed in this example:
[Telegram](https://build.opensuse.org/projects/home:MartinVonReichenberg:Network/packages/Telegram/files/Telegram.spec?expand=1)

There has been a **pull request** #65 addressing & fixing this issue, but it seems to persist in a more recent package compilations . . .

**Comment by Conan-Kudo** [comment]
Debian doesn't have `/usr/share/licenses`, so there's not really a reason to install there.

**Comment by Conan-Kudo** [comment]
If you want to manually install things there, you can by using `%license %{_datadir}/licenses/%{name}/*`.

**Comment by MartinVonReichenberg** [comment]
_Then the issue is it creates empty directories * `%{_datadir}/licenses/%{name}/` * as the end result of building . . ._

Perhaps an `rm -fdr` _or equivalent_  at the end when 'probing' %files %license section? 

_Now, OBS does not work with `/opt/` directory at all. One just wants to re-copy the original data and he cannot - for unknown reason -> leading to an empty DEB package with a successful build . . ._ ;-D

> Freakin' hardlocked untouchable directory.

**Comment by Conan-Kudo** [comment]
Ordinarily `%license` will install into the docdir. The spec file you linked to is doing it wrong anyway, you shouldn't be creating the doc or license directories yourself, as rpmbuild/debbuild will construct the correct paths for installing the data.

**Comment by Conan-Kudo** [comment]
There's a fair bit of things wrong with that spec file, actually. Even the way the working directory is setup is not exactly pristine. And aren't there examples of builds of telegram that actually build it from source? Both Fedora and openSUSE have them.

**Comment by MartinVonReichenberg** [comment]
> There's a fair bit of things wrong with that spec file, actually. Even the way the working directory is setup is not exactly pristine. And aren't there examples of builds of telegram that actually build it from source? Both Fedora and openSUSE have them.

Yeah, 
for TumbleWeed yes, for Leap no.

Also, there tend to be issues when compiling Telegram from source - even on Fedora _(RPMFusion)_ due to its compilation complexity. 

_So there I am . . ._
