### ISSUE TITLE
"%exclude" doesn't work in file lists

### ISSUE THREAD

**Issue by Conan-Kudo** [debbuild/debbuild#34]
The `%exclude` directive in file lists are used to prevent certain files from being included in a package/subpackage that would ordinarily be included.

However, debbuild doesn't know what to do with `%exclude` and dies.

**Comment by ailin-nemui** [comment]
I need this to separate .so file into -dev package and include .so* in main package

**Comment by Conan-Kudo** [comment]
This is now fixed with the merge and release of #195 as debbuild 22.02.1.
